import Head from "next/head";
import React, { ReactNode } from "react";

// import Banner from "./Banner";

import HeaderTest from "./HeaderTest";

type PropType = {
  children: ReactNode;
};

export default function Layout({ children }: PropType) {
  return (
    <div>
      <Head>
        <title>Jimdii</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.io" />
      </Head>

      <HeaderTest />
      <main>{children}</main>
    </div>
  );
}
