import Head from "next/head";
import { ReactNode } from "react";
import Sidemenu from "./Sidemenu";

type PropType = {
  children: ReactNode;
};

export default function Layout({ children }: PropType) {
  return (
    <>
      <Head>
        <title>Create Next app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <div className="w-full h-screen flex relative">
        <Sidemenu />
        <main className="w-full">{children}</main>
      </div>
    </>
  );
}
